/*
 * Generated by NatureLang Compiler (IR pipeline)
 * Do not edit this file directly.
 */

#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "naturelang_runtime.h"

/* Forward declarations */
long long isEven(long long num);
long long factorial(long long n);
long long sum(long long x);
void greet(long long name);

long long isEven(long long num) {
    long long _t5 = 0;
    long long _t6 = 0;
    long long _t7 = 0;
    int _t8 = 0;
    long long _t9 = 0;
    long long _t10 = 0;

    {
        long long rest = 0;
        _t5 = 2LL;
        _t6 = num % _t5;
        rest = _t6;
        _t7 = 0LL;
        _t8 = (rest == _t7);
        if (!(_t8)) goto L2;
        {
            _t9 = 1LL;
            return _t9;
        }
        goto L3;
L2:;
        {
            _t10 = 0LL;
            return _t10;
        }
L3:;
    }
}

long long factorial(long long n) {
    long long _t2 = 0;
    int _t3 = 0;
    long long _t4 = 0;

    {
        _t2 = 2LL;
        _t3 = (n < _t2);
        if (!(_t3)) goto L0;
        {
            _t4 = 1LL;
            return _t4;
        }
        goto L1;
L0:;
        {
            long long result = 0;
            result = n;
            return result;
        }
L1:;
    }
}

long long sum(long long x) {
    {
        long long result = 0;
        result = x;
        return result;
    }
}

void greet(long long name) {
    char* _t0 = NULL;
    char* _t1 = NULL;

    {
        _t0 = "Hello, ";
        printf("%s\n", _t0);
        printf("%lld\n", (long long)name);
        _t1 = "!";
        printf("%s\n", _t1);
    }
}

int main(int argc, char *argv[]) {
    (void)argc; (void)argv;

    char* _t11 = NULL;
    char* _t12 = NULL;
    long long _t13 = 0;
    long long _t14 = 0;
    long long _t15 = 0;
    char* _t16 = NULL;
    long long _t17 = 0;
    long long _t18 = 0;
    char* _t19 = NULL;
    long long _t20 = 0;
    long long _t21 = 0;
    long long _t22 = 0;
    int _t23 = 0;
    char* _t24 = NULL;
    char* _t25 = NULL;
    char* _t26 = NULL;

    {
        _t11 = "=== Function Examples ===";
        printf("%s\n", _t11);
        _t12 = "World";
        greet(_t12);
        long long sum_result = 0;
        _t14 = 5LL;
        _t15 = sum(_t14);
        sum_result = _t15;
        _t16 = "sum(5) = ";
        printf("%s\n", _t16);
        printf("%lld\n", (long long)sum_result);
        long long fact_result = 0;
        _t17 = 5LL;
        _t18 = factorial(_t17);
        fact_result = _t18;
        _t19 = "5! = ";
        printf("%s\n", _t19);
        printf("%lld\n", (long long)fact_result);
        long long test_num = 0;
        _t20 = 4LL;
        test_num = _t20;
        _t21 = isEven(test_num);
        _t22 = 1LL;
        _t23 = (_t21 == _t22);
        if (!(_t23)) goto L4;
        {
            _t24 = "4 is even";
            printf("%s\n", _t24);
        }
        goto L5;
L4:;
        {
            _t25 = "4 is odd";
            printf("%s\n", _t25);
        }
L5:;
        _t26 = "=== Done ===";
        printf("%s\n", _t26);
    }

    return 0;
}
