/*
 * Generated by NatureLang Compiler (IR pipeline)
 * Do not edit this file directly.
 */

#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "naturelang_runtime.h"

int main(int argc, char *argv[]) {
    (void)argc; (void)argv;

    char* _t0 = NULL;

    {
        char* message = "";
        _t0 = "Hello, World!";
        message = _t0;
        printf("%s\n", message);
    }

    return 0;
}
