/*
 * Generated by NatureLang Compiler (IR pipeline)
 * Do not edit this file directly.
 */

#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "naturelang_runtime.h"

static char _nl_input_buffer[4096];

int main(int argc, char *argv[]) {
    (void)argc; (void)argv;

    char* _t0 = NULL;
    char* _t1 = NULL;
    char* _t2 = NULL;
    char* _t3 = NULL;
    char* _t4 = NULL;
    char* _t5 = NULL;
    char* _t6 = NULL;
    char* _t7 = NULL;
    char* _t8 = NULL;
    char* _t9 = NULL;

    {
        _t0 = "Welcome to NatureLang!";
        printf("%s\n", _t0);
        char* userName = "";
        _t1 = "What is your name? ";
        printf("%s", _t1); fflush(stdout);
        fgets(_nl_input_buffer, sizeof(_nl_input_buffer), stdin); _nl_input_buffer[strcspn(_nl_input_buffer, "\n")] = 0; userName = strdup(_nl_input_buffer);
        _t2 = "Hello, ";
        printf("%s\n", _t2);
        printf("%s\n", userName);
        _t3 = "!";
        printf("%s\n", _t3);
        long long age = 0;
        _t4 = "How old are you? ";
        printf("%s\n", _t4);
        fgets(_nl_input_buffer, sizeof(_nl_input_buffer), stdin); _nl_input_buffer[strcspn(_nl_input_buffer, "\n")] = 0; age = nl_to_number(_nl_input_buffer);
        _t5 = "You are ";
        printf("%s\n", _t5);
        printf("%lld\n", (long long)age);
        _t6 = " years old";
        printf("%s\n", _t6);
        _t7 = "Using show";
        printf("%s\n", _t7);
        _t8 = "Using print";
        printf("%s\n", _t8);
        _t9 = "=== I/O Demo Complete ===";
        printf("%s\n", _t9);
    }

    return 0;
}
