/*
 * Generated by NatureLang Compiler (IR pipeline)
 * Do not edit this file directly.
 */

#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "naturelang_runtime.h"

int main(int argc, char *argv[]) {
    (void)argc; (void)argv;

    char* _t0 = NULL;
    long long _t1 = 0;
    long long _t2 = 0;
    double _t3 = 0;
    char* _t4 = NULL;
    int _t5 = 0;
    char* _t6 = NULL;
    long long _t7 = 0;
    char* _t8 = NULL;
    long long _t9 = 0;
    char* _t10 = NULL;
    long long _t11 = 0;
    char* _t12 = NULL;
    long long _t13 = 0;
    long long _t14 = 0;
    long long _t15 = 0;
    char* _t16 = NULL;
    int _t17 = 0;
    char* _t18 = NULL;
    char* _t19 = NULL;
    char* _t20 = NULL;
    char* _t21 = NULL;
    long long _t22 = 0;
    long long _t23 = 0;
    long long _t24 = 0;
    int _t25 = 0;
    char* _t26 = NULL;
    long long _t27 = 0;
    long long _t28 = 0;
    long long _t29 = 0;
    int _t30 = 0;
    long long _t31 = 0;
    long long _t32 = 0;
    char* _t33 = NULL;
    long long _t34 = 0;
    long long _t35 = 0;
    int _t36 = 0;
    char* _t37 = NULL;
    long long _t38 = 0;
    long long _t39 = 0;
    char* _t40 = NULL;
    char* _t41 = NULL;

    {
        _t0 = "=== NatureLang Full Feature Demo ===";
        printf("%s\n", _t0);
        long long x = 0;
        _t1 = 10LL;
        x = _t1;
        long long y = 0;
        _t2 = 25LL;
        y = _t2;
        double ratio = 0;
        _t3 = 2.5;
        ratio = _t3;
        char* label = "";
        _t4 = "demo";
        label = _t4;
        int ok = 0;
        _t5 = 1;
        ok = _t5;
        _t6 = "Section 1: declarations done";
        printf("%s\n", _t6);
        long long sum = 0;
        _t7 = x + y;
        sum = _t7;
        _t8 = "sum =";
        printf("%s\n", _t8);
        printf("%lld\n", (long long)sum);
        long long product = 0;
        _t9 = x * y;
        product = _t9;
        _t10 = "product =";
        printf("%s\n", _t10);
        printf("%lld\n", (long long)product);
        double division = 0;
        _t11 = y / x;
        division = _t11;
        _t12 = "division =";
        printf("%s\n", _t12);
        printf("%g\n", (double)division);
        long long complexResult = 0;
        _t13 = 2LL;
        _t14 = y * _t13;
        _t15 = x + _t14;
        complexResult = _t15;
        _t16 = "complex =";
        printf("%s\n", _t16);
        printf("%lld\n", (long long)complexResult);
        _t17 = (x < y);
        if (!(_t17)) goto L0;
        {
            _t18 = "x < y is true";
            printf("%s\n", _t18);
        }
        goto L1;
L0:;
        {
            _t19 = "x < y is false";
            printf("%s\n", _t19);
        }
L1:;
        if (!(ok)) goto L2;
        {
            _t20 = "ok flag is true";
            printf("%s\n", _t20);
        }
        goto L3;
L2:;
        {
            _t21 = "ok flag is false";
            printf("%s\n", _t21);
        }
L3:;
        long long score = 0;
        _t22 = 85LL;
        score = _t22;
        _t23 = 80LL;
        _t24 = 89LL;
        _t25 = ((score >= _t23) && (score <= _t24));
        if (!(_t25)) goto L4;
        {
            _t26 = "Grade band: B";
            printf("%s\n", _t26);
        }
L4:;
        long long counter = 0;
        _t27 = 0LL;
        counter = _t27;
        _t28 = 3LL;
        _t29 = 0LL;
L5:;
        _t30 = (_t29 >= _t28);
        if (_t30) goto L6;
        {
            _t31 = 1LL;
            _t32 = counter + _t31;
            counter = _t32;
            _t33 = "repeat counter:";
            printf("%s\n", _t33);
            printf("%lld\n", (long long)counter);
        }
L7:;
        _t29 = _t29 + 1LL;
        goto L5;
L6:;
        long long i = 0;
        _t34 = 0LL;
        i = _t34;
L8:;
        _t35 = 2LL;
        _t36 = (i < _t35);
        if (!(_t36)) goto L9;
        {
            _t37 = "while iteration";
            printf("%s\n", _t37);
            _t38 = 1LL;
            _t39 = i + _t38;
            i = _t39;
        }
        goto L8;
L9:;
        _t40 = "=== Demo Complete ===";
        printf("%s\n", _t40);
        _t41 = "=== Demo Complete ===";
        printf("%s\n", _t41);
    }

    return 0;
}
